--- #YAML:1.0
name:               AnyEvent-STOMP-Client
version:            0.1
abstract:           An event-based non-blocking STOMP 1.2 client based on AnyEvent and Object::Event.
author:
    - Raphael Seebacher <raphael@seebachers.ch>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:       7.04
    Object::Event:  1.23
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
